# Vagrantfile for development cluster VM for NVAL

## Get paths to ssh keys from env
ENV_PATH = ".env"
SSH_KEY_PATH = File.read(ENV_PATH).split("SSH_KEY_PATH=").last.strip

# Dictionary to store info of hosts.
host_info = {}

Vagrant.configure("2") do |config|
  # Configuration here will create default VMs
  # config.vm.box = "ubuntu/focal64"
  # config.vm.provision :shell, path: "bootstrap.sh"
  # config.vm.network :forwarded_port, guest: 80, host: 1234

  ## Main machine that runs NVAL
  config.vm.define "controller" do |controller|
    controller.vm.box = "ubuntu/jammy64"

    controller.vm.hostname = "controller.local"
    controller.vm.network "private_network", ip: "192.168.56.12", hostname: true
    controller.vm.network :forwarded_port, guest: 8000, host: 8000
    controller.vm.network :forwarded_port, guest: 8081, host: 8081
    controller.vm.network :forwarded_port, guest: 3333, host: 3333
    controller.vm.network :forwarded_port, guest: 3100, host: 3100
    controller.vm.network :forwarded_port, guest: 9090, host: 9090
    controller.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
    end
    host_info["controller.local"] = {
      "hostname" => "controller.local"
      "hostaddr" => "192.168.56.12"
    }
  end

  ## Worker machines that NVAL uses to deploy blockchain
  (1..4).each do |i|
    config.vm.define "nval_#{i}" do |nval|
      nval.vm.box = "ubuntu/focal64"
      nval.vm.hostname = "nval#{i}.local"
      nval.vm.network "private_network", ip: "192.168.56.#{12 + i}", hostname: true
      nval.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 1
      end
      host_info["nval#{i}.local"] = {
        "hostname" => "nval#{i}.local"
        "hostaddr" => "192.168.56.#{12 + i}"
      }
    end
  end

  # These provisioning would run on all VMs
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision "file", source: SSH_KEY_PATH, destination: "~/.ssh/"
  config.vm.provision "shell", path: "set_authorised_keys.sh"
  config.vm.provision "shell", inline: <<-SHELL
    fallocate -l 1G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab
  SHELL
# Write the host_info hash to an Ansible hosts file
File.open("ansible_hosts", "w") do |file|
  file.puts "[controller]"
  file.puts host_info["controller.local"]["hostaddr"]

  file.puts "\n[nval]"
  (1..4).each do |i|
    file.puts host_info["nval#{i}.local"]["hostaddr"]
  end
end

end
