# Vagrantfile for development cluster VM for NVAL

## Get paths to ssh keys from env
# ENV_PATH = ENV['ENV_PATH'] || ".env"
# SSH_KEY_PATH = File.read(ENV_PATH).split("SSH_KEY_PATH=").last.strip
SSH_KEY_PATH = ENV['SSH_KEY_PATH'] || "~/.ssh/id_rsa.pub"
WORKING_DIR = ENV['STACK_STARTER_WORKING_DIR'] || "/tmp/stack_starter/"
PROVISION_ID = ENV['STACK_STARTER_PROVISION_ID'] || "tmp_provision_id"

# Dictionary to store info of hosts.
host_info = {}

Vagrant.configure("2") do |config|
  # Configuration here will create default VMs
  # config.vm.box = "ubuntu/focal64"
  # config.vm.provision :shell, path: "bootstrap.sh"
  # config.vm.network :forwarded_port, guest: 80, host: 1234

  ## Main machine that runs NVAL
  config.vm.define "controller" do |controller|
    controller.vm.box = "ubuntu/jammy64"

    controller.vm.hostname = "controller.local"
    controller.vm.network "private_network", ip: "192.168.56.12", hostname: true
    controller.vm.network :forwarded_port, guest: 8000, host: 8000
    controller.vm.network :forwarded_port, guest: 8081, host: 8081
    controller.vm.network :forwarded_port, guest: 3333, host: 3333
    controller.vm.network :forwarded_port, guest: 3100, host: 3100
    controller.vm.network :forwarded_port, guest: 9090, host: 9090
    controller.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
    end
    host_info["controller.local"] = {
      "hostname" => "controller.local"
      "hostaddr" => "192.168.56.12"
    }
  end # End controller provision

  ## Worker machines that NVAL uses to deploy blockchain
  (1..4).each do |i|
    config.vm.define "nval_#{i}" do |nval|
      nval.vm.box = "ubuntu/focal64"
      nval.vm.hostname = "nval#{i}.local"
      nval.vm.network "private_network", ip: "192.168.56.#{12 + i}", hostname: true
      nval.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 1
      end
      host_info["nval#{i}.local"] = {
        "hostname" => "nval#{i}.local"
        "hostaddr" => "192.168.56.#{12 + i}"
      }
    end
  end # End worker provision

  # These provisioning would run on all VMs
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision "file", source: SSH_KEY_PATH, destination: "~/.ssh/"
  config.vm.provision "shell", path: "set_authorised_keys.sh"
  config.vm.provision "shell", inline: <<-SHELL
    fallocate -l 1G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab
  SHELL

  require 'fileutils'

  # Ensure the directory exists
  FileUtils.mkdir_p("#{WORKING_DIR}/#{PROVISION_ID}")
  File.open("#{WORKING_DIR}/#{PROVISION_ID}/hosts.ini", "w") do |file|
    file.puts "[controller]"
    file.puts "controller ansible_host=#{host_info["controller.local"]["hostaddr"]} ansible_user=vagrant"

    file.puts "\n[worker]"
    (1..4).each do |i|
      file.puts "worker_#{i} ansible_host=#{host_info["nval#{i}.local"]["hostaddr"]} ansible_user=vagrant"
    end
  end # End File operation

end # End vagrant configuration
